#! /bin/bash
cd ~/
wget https://raw.githubusercontent.com/jteske54/linux/master/.zshrc
cp ~/.zshrc /etc/skel/.zshrc
cp ~/.zshrc /root/.zshrc
sed -i 's/bash/zsh/g' /etc/passwd
sed -i 's/bash/zsh/' /etc/adduser.conf
cd /etc/lightdm
wget https://raw.githubusercontent.com/jteske54/linux/master/ubuntu/lightdm.conf
apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
apt-get install openssh-server apache2 mysql-server php5 libapache zsh vim gdebi dconf-tools network-manager-openvpn-gnome openvpn easy-rsa exfat-utils exfat-fuse -y
reboot
