#! /bin/bash
cd ~/
wget https://raw.githubusercontent.com/jteske54/linux/master/.zshrc
cp ~/.zshrc /etc/skel/.zshrc
cp ~/.zshrc /root/.zshrc
sed -i 's/bash/zsh/g' /etc/passwd
sed -i 's/bash/zsh/' /etc/adduser.conf
cd /etc/lightdm
wget https://raw.githubusercontent.com/jteske54/linux/master/ubuntu/lightdm.conf
apt-get update
apt-get install zsh vim gdebi dconf-tools -y
reboot
